### ISSUE TITLE
How to obfuscate a random function in a program?

### ISSUE THREAD

**Issue by zyfeng-go** [RUB-SysSec/loki#2]
Hi there, I'm reaching out to request help with an issue I've encountered while trying to obfuscate a random function in a program. Your documentation has been exceptionally clear and easy to follow, but I ran into a problem when I attempted to obfuscate a function I had created in a program.

Here's a step-by-step rundown of what I did:

1. I created a file named `hello.cpp` and placed it under `loki/testcases/real_world_crypto`.
2. The source code for `hello.cpp` is as follows:
```
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <chrono>
#include <string>

extern "C" long target_function()
{
  uint32_t len = 5;
  for(int i = 0; i < 10; i++)
      len += i;
  return len;
}

int main(int argc, char *argv[]) {
  target_function();
}
```
3. I attempted to obfuscate `target_function` with the command `python3 obfuscate.py --allow hello --instances 1 /home/user/evaluation/hello`. Unfortunately, it resulted in the following error:
```
INFO: Path for evaluation: /home/user/evaluation/hello
INFO: Base directory: /home/user/loki/loki
INFO: Maximum number of cores: 16
INFO: Number of instances: 1
INFO: Timeout: 10800
INFO: #Verification iterations: 1000
...
...
DEBUG: Copied lift_input, generate-vm-9.0, and template.bc to /home/user/evaluation/hello/bin
INFO: Found 1 testcases
INFO: Inspecting hello.cpp (1/1)
/home/user/loki/loki/testcases/real_world_crypto/hello.cpp
DEBUG: Executing /llvm/bin/clang -c -emit-llvm --std=c++14 -O3 -Xclang -disable-llvm-passes /home/user/evaluation/hello/workdirs/hello/src/input_program.cpp -o /home/user/evaluation/hello/workdirs/hello/src/input_program.bc
DEBUG: Executing /home/user/evaluation/hello/bin/lift_input /home/user/evaluation/hello/workdirs/hello/src
ERROR: LIFTER: Lifting failed with:
 ['Could not translate an instruction:  ret i64 50']
ERROR: Failed to lift source program's bitcode to TIL
```

You previously noted, _If you are interested in obfuscation, head to [loki](https://github.com/RUB-SysSec/loki/blob/main/loki), which is our prototype implementation capable of obfuscating code (**with limitations**)_. However, I'm unclear about the limitations you mentioned.

I'd greatly appreciate any guidance or suggestions to resolve the issue. Thank you in advance for your help!

**Comment by mu00d8** [comment]
Hey,

at the first glance, your program appears to be simple enough such that the compiler optimizes the function to `return 50` (see https://godbolt.org/z/WjW77nqrz). It does indeed look like our lifter cannot handle the case when only a constant value is returned but I'm not sure if handling that makes much sense.
To avoid the optimization from removing your loop, you can try to make it input-dependent - for example:
```cpp
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <chrono>
#include <string>

extern "C" long target_function(uint64_t argument)
{
  uint32_t len = 5;
  for(int i = 0; i < 10; i++)
      len += (i * argument);
  return len;
}

int main(int argc, char *argv[]) {
    uint64_t argument = std::stoull(argv[1]);
    target_function(argument);
}
```

This will compile to https://godbolt.org/z/3d1E7MjYz - can you try whether this works as expected?

**Comment by zyfeng-go** [comment]
THANK YOU for the swift response. The modified code snippet worked perfectly fine!

However, I must apologize as I forgot to mention something important in my initial post. I've previously also tried disabling the optimization, yet the lifter still failed to translate some of the instructions.

For the same source code:
```
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <chrono>
#include <string>

extern "C" long target_function()
{
  uint32_t len = 5;
  for(int i = 0; i < 10; i++)
      len += i;
  return len;
}

int main(int argc, char *argv[]) {
  target_function();
}
```

Here are the steps I followed:

1. I ran the command `/llvm/bin/clang -c -emit-llvm --std=c++14 -O0 -Xclang -disable-llvm-passes /home/user/evaluation/hello/workdirs/hello/src/input_program.cpp -o /home/user/evaluation/hello/workdirs/hello/src/input_program.bc` with the optimization level set to 0 instead of 3.
2. I attempted to lift the program with the command `lift_input /home/user/evaluation/hello/workdirs/hello/src`.

Regrettably, the lifter produced the following errors:
```
Could not translate an instruction:  br label %3
Could not translate an instruction:  br i1 %5, label %6, label %13
Could not translate an instruction:  br label %10
Could not translate an instruction:  br label %3
Could not translate an instruction:  ret i64 %15
Done.
```

I'm wondering if you might have any insight into why's that. Thank you!

**Comment by mu00d8** [comment]
I'm afraid but that's where you hit one of the aforementioned limitations: the prototype doesn't support `br`; we've never used it for O0 code and LLVM's powerful optimization passes were sufficient for all our purposes
