### ISSUE TITLE
Cargo Version on the Rustup toolchain list

### ISSUE THREAD

**Issue by zhangnaiqian** [RUB-SysSec/loki#3]
Hi there, I was wondering if I could have the version of the Cargo on the Rustup toolchain list you used in the Loki obfuscator?  Because when build the Loki obfuscator, I met some issues about Cargo version, I tried to use some versions between 1.50 and 1.60, but did not work. Thank you very much for any help!

**Comment by mu00d8** [comment]
We should have pinned the version, sorry. Taking a quick look, I didn't find anything giving away the one we used originally. But when looking into an issue with our case study recently, I had a working setup based on the following:
```bash
$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.74.0-nightly (c469197b1 2023-08-22)`
```

I've also just added the Cargo.lock to https://github.com/RUB-SysSec/loki/tree/case-study to avoid problems with the dependencies - can you check out this branch and see if this addresses your issues?

**Comment by zhangnaiqian** [comment]
Thanks for the quick response! I checked out the branch to the case-study, and updated the rustup version like:

rustup --version      
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.74.0 (79e9716c9 2023-11-13)`

cannot switch to the nightly version on 1.74.0, not sure if this is a cause. 

For now, I still have the issue like the screenshot
![Screenshot from 2024-01-23 11-54-14](https://github.com/RUB-SysSec/loki/assets/25166999/1acd3a88-4aaf-4d74-b4a0-5e95be1d7936)

**Comment by mu00d8** [comment]
Have you tried deleting these two lines
```toml
[lints]
needless_return = "allow"
```
from  `/home/user/loki/loki/obfuscator/intermediate_langauge/Cargo.toml`? Looks like the linter settings are incompatible, but they aren't really needed here

**Comment by zhangnaiqian** [comment]
All set, thank you very much for your help!
